name: IBM Cloud Auto Restart

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
#   schedule:
#     - cron: '00 22 * * 3'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        pwd
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
        IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
      run: |
        rm -rf v2ray-cloudfoundry
        git clone https://github.com/a132395/v2ray-cloudfoundry.git
        wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
        unzip -o v2ray-linux-64.zip "v2ray" "v2ctl" "geosite.dat" "geoip.dat" 
        cp -f "v2ray" "v2ctl" "geosite.dat" "geoip.dat"  v2ray-cloudfoundry/v2ray/.
        rm -rf v2ray-linux-64.zip
        chmod 700 v2ray v2ctl
        chmod +x /home/runner/work/IBMYes/IBMYes/v2ray-cloudfoundry/v2ray/*
        cd v2ray-cloudfoundry
        sed -i "s/GetStartedGo/${{ secrets.IBM_APP_NAME }}/g"  /home/runner/work/IBMYes/IBMYes/v2ray-cloudfoundry/manifest.yml
        #sed -i "s/8c35bef3-d51f-41ab-ac87-7b053410495b/${{ secrets.UUID }}/g"  /home/runner/work/IBMYes/IBMYes/v2ray-cloudfoundry/v2ray/config.json
        #sed -i "s:/:${{ secrets.PATH }}:"  /home/runner/work/IBMYes/IBMYes/v2ray-cloudfoundry/v2ray/config.json
        sed -i "s/128/256/g"  /home/runner/work/IBMYes/IBMYes/v2ray-cloudfoundry/manifest.yml
        #/home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud target -r eu-gb
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID"
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud target --cf
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud cf install
        /home/runner/work/IBMYes/IBMYes/IBM_Cloud_CLI/ibmcloud cf push
